
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
  image:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - 
         name: Login to docker hub
         uses: mr-smithers-excellent/docker-build-push@v4
         with:
            image: ${{ secrets.DOCKER_IMAGE }}
            registry: ${{ secrets.REGISTRY }}
            username: ${{ secrets.DOCKER_USER_NAME }}
            password: ${{ secrets.PASSWORD }}